name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
        bundler-cache: true

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --modules-folder _assets/yarn --production

    - name: build
      run: bundle exec jekyll build

    - name: deploy
      run: |
        sudo chown -R $USER:$USER /home/runner/work/cloudblurbs.com/cloudblurbs.com/
        chmod +x ./bin/automated
        ./bin/automated
      env:
        USER_NAME: gh deployer
        USER_EMAIL: deployer@github-actions.com
